### ISSUE TITLE
Figure out incompatibility between rspec and 'stop' killing the process group

### ISSUE THREAD

**Issue by codebudo** [SerenovaLLC/winter#8]
When `rake spec` is run and the systems tests are performed, the 'stop' method finds the pid of the current process (which is rspec) and kills it. This prevents the test from running successfully.

**Comment by dlind** [comment]
This has been fixed. 
The issue was that stop attempted to stop things by issuing a kill by process group id. 
Because by default pgid is inherited from the the parent process rake had the same group as winter so winter's kill signal was being propagated to rake as well as the child process. 

https://github.com/dlind/winter/compare/8afd27c01dcfef44680836a5a0572c60c06a6b8a%5E...050659aae1b7ea336e186c66e5d69eb24019e9f8

**Comment by codebudo** [comment]
Sweet.
